name: PR Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches:
      - '**' # Trigger on all branches

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PLAYWRIGHT_SKIP_BROWSER_GC: 1 # Stop playwright from deleting unused browsers (cache might be old but still very much valid)
  SKIP_BUILD_FOR_TESTS: 1 # Used in playwright.config.ts

jobs:
  # Job to set up common environment
  setup:
    name: Set up environment
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.node-version.outputs.version }}
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up pnpm
      - uses: pnpm/action-setup@v4
        name: Install NodeJS dependency manager (PNPM)
        with:
          version: 9
          run_install: false

      # Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # SvelteKit Sync
      - name: SvelteKit Sync
        run: pnpm sync

      # SvelteKit Build
      - name: SvelteKit Build
        run: pnpm build

  # Job to run Svelte checks
  check_svelte:
    name: Run Svelte checks
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run Svelte checks
        run: pnpm check:svelte

  # Job to check linting (ESLint)
  lint:
    name: Check linting (ESLint)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: Check linting (ESLint)
        run: pnpm check:lint

  # Job to check formatting
  format:
    name: Check formatting (Prettier)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: Check formatting (Prettier)
        run: pnpm check:format

  # Job to run unit tests (Vitest)
  unit_tests:
    name: Run unit tests (Vitest)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests (Vitest)
        run: pnpm test:unit

  # Job to run E2E tests (Playwright) only if the previous jobs succeed
  e2e_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: [check_svelte, lint, format, unit_tests] # Only run if these jobs succeed
    steps:
      # Get installed Playwright version
      - name: Get installed Playwright version
        id: playwright-version
        run: echo -n "::set-output name=version::$(npm ls @playwright/test --json | jq --raw-output '.dependencies["@playwright/test"].version')"

      # Restore Playwright browser binaries cache
      - uses: actions/cache@v4
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      # Install Playwright
      - name: Install Playwright
        run: npx playwright install --with-deps

      # Run E2E Tests (Playwright)
      - name: Run E2E Tests
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
